/**
 * serenity-stock-profiles.js
 *
 * Hand-curated per-ticker metadata for Serenity's thesis stocks, scraped
 * from trackserenity.com's public /script.js. The site ships a static
 * `stockProfiles` map that includes mentionPrice, mentionDate, sector,
 * exchange, and a human-written "relation" note explaining why Serenity
 * cares about the name.
 *
 * We treat this as the **primary** source for mention-day prices because:
 *   - The author of trackserenity.com has manually verified these values
 *   - They match exactly what the public site renders
 *   - Yahoo Finance is currently 429-throttling residential IPs
 *
 * For tickers NOT in this map, the pipeline falls back to Yahoo Finance.
 *
 * Auto-regenerated by scripts/refresh-stock-profiles.js (run occasionally).
 */

export const STOCK_PROFILES = {
  "009150": {
    "name": "Samsung Electromechanics",
    "exchange": "KRX",
    "sector": "Electronic components",
    "logo": "https://logo.clearbit.com/samsungsem.com",
    "note": "Samsung Group subsidiary producing MLCC, camera modules, and semiconductor substrates.",
    "relation": "Serenity highlighted Samsung Electromechanics as a key player in the advanced glass substrate supply chain for AI packaging.",
    "mentionDate": "2026-06-07",
    "mentionPrice": 329000
  },
  "011790": {
    "name": "SKC",
    "exchange": "KRX",
    "sector": "Advanced materials",
    "logo": "https://logo.clearbit.com/skc.co.kr",
    "note": "SK Group affiliate; SKC Absolics subsidiary is a first-mover in glass substrate for advanced packaging.",
    "relation": "SKC's subsidiary, Absolics, is recognized as a first-mover in glass substrate technology for AI accelerators.",
    "mentionDate": "2026-06-07",
    "mentionPrice": 142300
  },
  "688017": {
    "name": "LeaderDrive",
    "exchange": "SSE",
    "sector": "Humanoid robotics",
    "logo": "",
    "note": "Shanghai STAR Market company with leading harmonic reducer market share for humanoid robot supply chains.",
    "relation": "Serenity's top-conviction pick in China for the humanoid robotics supply chain, highlighting their market-leading harmonic reducers.",
    "mentionDate": "2026-06-05",
    "mentionPrice": 362.43
  },
  "AAOI": {
    "name": "Applied Optoelectronics",
    "exchange": "NASDAQ",
    "sector": "Optical networking",
    "logo": "https://logo.clearbit.com/ao-inc.com",
    "note": "Datacenter optical transceiver supplier targeting 800G/1.6T for AI networking infrastructure.",
    "relation": "One of Serenity's core high-conviction CPO/photonics plays, tied to high-speed optical transceivers.",
    "mentionDate": "2026-06-05",
    "mentionPrice": 177
  },
  "ALAB": {
    "name": "Astera Labs",
    "exchange": "NASDAQ",
    "sector": "Semiconductor connectivity",
    "logo": "https://logo.clearbit.com/asteralabs.com",
    "note": "Semiconductor connectivity provider for AI datacenters and PCIe switches.",
    "relation": "A major high-conviction semiconductor connectivity play, recently added to the Nasdaq-100 index.",
    "mentionDate": "2026-06-12",
    "mentionPrice": 372
  },
  "AMAT": {
    "name": "Applied Materials",
    "exchange": "NASDAQ",
    "sector": "Semiconductor equipment",
    "logo": "",
    "note": "",
    "relation": "",
    "mentionDate": "2026-06-07",
    "mentionPrice": 453.01
  },
  "AMD": {
    "name": "Advanced Micro Devices",
    "exchange": "NASDAQ",
    "sector": "Semiconductors",
    "logo": "",
    "note": "",
    "relation": "",
    "mentionDate": "2026-06-07",
    "mentionPrice": 466.38
  },
  "ASX": {
    "name": "ASE Technology",
    "exchange": "NYSE",
    "sector": "Semiconductor packaging",
    "logo": "",
    "note": "",
    "relation": "",
    "mentionDate": "2026-06-06",
    "mentionPrice": 34.03
  },
  "AVGO": {
    "name": "Broadcom",
    "exchange": "NASDAQ",
    "sector": "Semiconductors",
    "logo": "",
    "note": "",
    "relation": "",
    "mentionDate": "2026-06-07",
    "mentionPrice": 385.73
  },
  "AXTI": {
    "name": "AXT Inc",
    "exchange": "NASDAQ",
    "sector": "Semiconductor substrates",
    "logo": "",
    "note": "",
    "relation": "",
    "mentionDate": "2026-06-07",
    "mentionPrice": 89.04
  },
  "INTC": {
    "name": "Intel",
    "exchange": "NASDAQ",
    "sector": "Semiconductors",
    "logo": "",
    "note": "",
    "relation": "",
    "mentionDate": "2026-06-07",
    "mentionPrice": 99.17
  },
  "IQE": {
    "name": "IQE plc",
    "exchange": "LSE",
    "sector": "Compound semiconductors",
    "logo": "",
    "note": "",
    "relation": "",
    "mentionDate": "2026-06-07",
    "mentionPrice": 45
  },
  "LITE": {
    "name": "Lumentum",
    "exchange": "NASDAQ",
    "sector": "Photonics",
    "logo": "",
    "note": "",
    "relation": "",
    "mentionDate": "2026-06-09",
    "mentionPrice": 821.76
  },
  "MRVL": {
    "name": "Marvell Technology",
    "exchange": "NASDAQ",
    "sector": "Semiconductors",
    "logo": "",
    "note": "",
    "relation": "",
    "mentionDate": "2026-06-06",
    "mentionPrice": 263.47
  },
  "MU": {
    "name": "Micron Technology",
    "exchange": "NASDAQ",
    "sector": "Memory",
    "logo": "",
    "note": "",
    "relation": "",
    "mentionDate": "2026-06-05",
    "mentionPrice": 864.01
  },
  "NBIS": {
    "name": "Nebius Group",
    "exchange": "NASDAQ",
    "sector": "AI infrastructure",
    "logo": "",
    "note": "",
    "relation": "",
    "mentionDate": "2026-06-07",
    "mentionPrice": 227.81
  },
  "NVDA": {
    "name": "NVIDIA",
    "exchange": "NASDAQ",
    "sector": "Semiconductors",
    "logo": "",
    "note": "",
    "relation": "",
    "mentionDate": "2026-06-05",
    "mentionPrice": 205.1
  },
  "PL": {
    "name": "Planet Labs",
    "exchange": "NYSE",
    "sector": "Earth observation",
    "logo": "",
    "note": "",
    "relation": "",
    "mentionDate": "2026-06-05",
    "mentionPrice": 32.22
  },
  "RDDT": {
    "name": "Reddit",
    "exchange": "NYSE",
    "sector": "Social media",
    "logo": "",
    "note": "",
    "relation": "",
    "mentionDate": "2026-06-04",
    "mentionPrice": 183.91
  },
  "RKLB": {
    "name": "Rocket Lab USA",
    "exchange": "NYSE",
    "sector": "Aerospace",
    "logo": "",
    "note": "",
    "relation": "",
    "mentionDate": "2026-06-12",
    "mentionPrice": 110.08
  },
  "RPI": {
    "name": "Raspberry Pi Holdings",
    "exchange": "LSE",
    "sector": "Single-board computers",
    "logo": "",
    "note": "",
    "relation": "",
    "mentionDate": "2026-06-05",
    "mentionPrice": 283
  },
  "SIVE": {
    "name": "Sivers Semiconductors",
    "exchange": "OMX Stockholm",
    "sector": "Semiconductors",
    "logo": "",
    "note": "",
    "relation": "",
    "mentionDate": "2026-06-04",
    "mentionPrice": 86.75
  },
  "SNDK": {
    "name": "SanDisk",
    "exchange": "NASDAQ",
    "sector": "Memory",
    "logo": "",
    "note": "",
    "relation": "",
    "mentionDate": "2026-06-10",
    "mentionPrice": 1643.23
  },
  "TSEM": {
    "name": "Tower Semiconductor",
    "exchange": "NASDAQ",
    "sector": "Semiconductors",
    "logo": "",
    "note": "",
    "relation": "",
    "mentionDate": "2026-06-06",
    "mentionPrice": 235.48
  },
  "TSM": {
    "name": "TSMC",
    "exchange": "NYSE",
    "sector": "Semiconductors",
    "logo": "",
    "note": "",
    "relation": "",
    "mentionDate": "2026-06-05",
    "mentionPrice": 415.17
  },
  "XFAB": {
    "name": "X-FAB Silicon Foundries",
    "exchange": "Euronext Paris",
    "sector": "Semiconductors",
    "logo": "",
    "note": "",
    "relation": "",
    "mentionDate": "2026-06-06",
    "mentionPrice": 10.26
  }
};